### PR TITLE
Properly download robin_map

### PR DESCRIPTION
**Pull request by xhochy**
This is the preferred way to download and attribute additional sources.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
@conda-forge/nanobind This is ready for review.

**Comment by wjakob** [comment]
Please do *not* change the license. This project uses the 3-clause BSD license, which subsumes the terms of the MIT license.

**Comment by xhochy** [comment]
I have added the `AND MIT` because this is vendoring `ext/robin_map` which is MIT-licensed. We don't have a real policy on what to put into the field for vendored dependencies. Any opinions on this matter @conda-forge/core?

**Comment by dopplershift** [comment]
Without a doubt, the license file from robin_map needs to be included. It explicitly says this in its (MIT) license:

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

Strictly speaking, based on that, the package is covered by the terms of both BSD3 and MIT licenses, no?

**Comment by wjakob** [comment]
My perspective as creator of this project is that the MIT license requirement you mentioned is trivially addressed by shipping the source code of the header file along with the project (which is always the case for nanobind, it's a pure source code package).

The license of the project itself is the BSD 3-clause license, which subsumes the MIT license (two of the three BSD license clauses cover the same requirements as that of the MIT license). I don't want to complicate the top-level license declaration of this project by listing separate licenses.

**Comment by xhochy** [comment]
I removed the `AND MIT`, so this should be ready now. We have no conda-forge wide policy about the SPDX expression, so I'll leave it up to the maintainer.

**Pull request merged**
